# Generated by Django 6.0.4 on 2026-05-14 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_id', models.CharField(max_length=20, unique=True)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('is_notify_driver', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['truck_id'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer_id', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('maker', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('load_capacity', models.DecimalField(decimal_places=2, help_text='Load capacity in tons or kg', max_digits=10)),
                ('trailer_type', models.CharField(choices=[('dolly', 'Dolly'), ('trailer', 'Trailer'), ('b_train', 'B-Train')], help_text='Type of trailer (Dolly, Trailer, B-Train)', max_length=50)),
                ('axle_count', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under maintenance'), ('idle', 'Idle')], default='idle', max_length=50)),
                ('truck_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='vehicle.truck')),
            ],
            options={
                'ordering': ['trailer_id'],
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tractor_id', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('maker', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('axle_count', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under maintenance'), ('idle', 'Idle')], default='idle', max_length=50)),
                ('truck_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tractor', to='vehicle.truck')),
            ],
            options={
                'ordering': ['tractor_id'],
            },
        ),
    ]
