# Generated by Django 6.0.4 on 2026-05-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_truck_id'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_id', models.CharField(max_length=20, unique=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('is_notify_driver', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['trip_id'],
            },
        ),
        migrations.RemoveField(
            model_name='tractor',
            name='truck_id',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='truck_id',
        ),
        migrations.AlterField(
            model_name='tractor',
            name='axle_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripDriverRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_driver_relations', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_driver_relations', to='vehicle.trip')),
            ],
            options={
                'unique_together': {('trip', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='TripTractorRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_tractor_relations', to='vehicle.tractor')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_tractor_relations', to='vehicle.trip')),
            ],
            options={
                'unique_together': {('trip', 'tractor')},
            },
        ),
        migrations.CreateModel(
            name='TripTrailerRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_trailer_relations', to='vehicle.trailer')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_trailer_relations', to='vehicle.trip')),
            ],
            options={
                'unique_together': {('trip', 'trailer')},
            },
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
