# Generated by Django 6.0.4 on 2026-05-20 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_trip_remove_tractor_truck_id_remove_trailer_truck_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triptractorrel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='triptractorrel',
            name='tractor',
        ),
        migrations.RemoveField(
            model_name='triptractorrel',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicle.tractor'),
        ),
        migrations.DeleteModel(
            name='TripDriverRel',
        ),
        migrations.DeleteModel(
            name='TripTractorRel',
        ),
    ]
