# Generated by Django 6.0.4 on 2026-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_triptractorrel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='axle_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_type',
            field=models.CharField(choices=[('dolly', 'Dolly'), ('trailer', 'Trailer'), ('b_train', 'B-Train')], default='trailer', help_text='Type of trailer (Dolly, Trailer, B-Train)', max_length=50),
        ),
    ]
