# Generated by Django 6.0.4 on 2026-05-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_trailer_axle_count_alter_trailer_trailer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicle.tractor'),
        ),
    ]
