# Generated by Django 6.0.4 on 2026-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_trip_tractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trailer',
            field=models.ManyToManyField(related_name='trips', through='vehicle.TripTrailerRel', to='vehicle.trailer'),
        ),
    ]
