# Generated by Django 6.0.4 on 2026-05-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_truck_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='truck_id',
        ),
    ]
